language: node_js

node_js:
- "node"

sudo: required

cache:
  directories:
    - node_modules

services:
  - postgresql
  - docker

addons:
  postgresql: "9.6"

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=postgresql://postgres@localhost/base63
  - DATABASE_MIGRATIONS_DIR=./migrations
  - DATABASE_MIGRATIONS_TABLE=migrations_identity
  - PGSSLMODE=require
  - ORIGIN=null
  - CLIENTS=null
  - AUTH0_CLIENT_ID=null
  - AUTH0_DOMAIN=null
  - LOGGLY_TOKEN=null
  - LOGGLY_SUBDOMAIN=null
  - ROLLBAR_TOKEN=null
  - GEMFURY_USER=base63
  # GEMFURY_API_KEY=???
  - secure: "OeCqWdNtSUOAB6MznuwwXVV3FrwTxjbn/m/4ekn83kdl06/gadJ6pKl/lRjZ1uv8cxUzgoR2vVxtIeN9nDcWzvyw5e5vVFvtD5XMzHLrs5knXzO0jl/eCLPRj+IruryQCKms73jBbvJb1OqojeeTmidY7ZpvuW8aWIS4bwTRJaMc8VLjsTk0qExYAD8ZyzpKNOZCIaXxiG97/mq+DwspJ3pOQzLpczciNy8l2Hl1nnyCYwfxadiwe0dNaUVSqezgA3ONzXwD3Hiadc/GoU961yPc6PqdlI3QA0HDx3fDP+2nATQw1BBSrf+OlDwmoVeNRcBcHQ1mg3gNnqRlhNWJvGfR+EMaau6/POH5jirtrnOBYA+c9+VhRblsNNnsIsFxKJkXx5iPXjlOCfpgcNKD7YL+dj1mCnkX/dKYdIQejeuQKtjUsDNeXvAiRB5d/D0rLp5HQzmI2A9IYaBUVPIXlVrYohUUULsCF0+AS0MpXe8j53SWAa4ry8HeYh39Kumh3ZEPYoJ/4SpMfNmHIQ+C0TtoK6zrO1neNwvpmnE41pG4zb7xN8yZHDRvkRo4rMPJ3QAnNma4VeLtFXql865qThj5DMqn0lPoQeHcIe3ZV+Zh9ab6KP0ape8LI9SZyd4chvqoDRbaFz6PeIcrsi+Z6paSIQNLxkal6RUi/9T05as="
  - DOCKER_HUB_USERNAME=horia141
  # DOCKER_HUB_PASSWORD
  - secure: "YRn6wE8iDxArGZVUp+mh3t0OfL+yVSs8Leq7hxFNu+ZIfuYENrXGD97SqiX+soHkFUzyUQG++kxRyyPXhdacJd1i7sYFzkMY3NpDf5/sZmmwANtcIqmcRXz5ytWO6BRiRlMEv7Y6SWcCYNwy2T4LU5BPgQXeU8vRv9UkLpK4PIXNbl8fq54tYstTC65QNtg0QjpvoEGzMEYhl7opcwuUuXar4mkzcW5GBTZPQryymGCXcuOCS+aWndjjCPuglZszDZeMrL8VhDadk8qdV2d6pG7Xv3DeBaxIn2rpZzvi0juQdrv7ti6mSUlkBMyR/Ri6wHTHtaRgqBfLae9DBA6rFTwjMi3y5IjbjAZbCYyOGmpGL39iO5BPx7blnajZ/KVvsjDv4FjM3mGrIUyXbP1rEEvCYn3Ot+2T7eo2YuRqXdkEQRNCm2fSVYF1eCHuHhJWgqY5TfYN4ufzjEVU3iJDwS5RfTxpza2F7fQYCsmidCEsQDrBRvoVi/kksA3mGpzjwnFNlXxbbc4G7IF+T1wYEXvLdkvy0yRg3pWofJhVBCrEawevUZUEmIce0DI6e3MuTwhwLFeftdUVpkRK1BAyh8fQJqDI55hMeW02cjCO4jlQfRgXGId5rpi4vhxQii9NIt9+xU3Ognl4ww0KPc+wyAdcGGmpACUuTR6UgfUks4w="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

before_script:
- psql -c 'create database base63;' -U postgres

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: docker build --tag base63/identity:$TRAVIS_TAG . && docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" && docker push base63/identity:$TRAVIS_TAG
  on:
    tags: true
# - provider: heroku
#   skip_cleanup: true
#   app: identity-staging-base63
#   api_key:
#     secure: "bkrJktWntQN9CX+C1/u3Hbg81EeJ7siSN6qgYC8l92vCe7KiguxpXa8LyYUmw/rtmCOBrYx51QWzBc2ivaDgrfFepjA4cMDgkTGUwCEJOYwos9Dq1S6AlQPiCsPoI/GtLCPbJf7cntf8iqJiMt4GfqUDEfvagCF5qOiphQtjmCY3wrFcDDB1PgbsBTYq596eEgKr1OcLt8965AL6Krad36WcpMRTTtqVujZdFR3U+VCWCfLd6N6NAWWt8+wUkjMmK2qzv8r1QyUDfmlJbhoh9SrTmP7nIjqhGmo0NTM/j4ANOic+17xhY9I93qTjpmiFO9OZcpa24L/928wMKYB0TH7EppRoODWzOd0PNdYtY3b5BWo2Uxt+HJPH9Mh9GL76A/6mlxNUTzKRo3/uiLloIWQLmEpETjbdMwS2YVpNrsBAEjdS1LO1NkesDXqzyxelODxTNn31tbfGvT/HAPq1/GhDy7gJa3MPdEAMaTMqfOM/Ursejx4sSrJDgsXKG0equJOwTrGY55NGkUUABUDJOM4hMkars/9Q88S+wVWUyV6ruWoKfDy/ljhBSBooT0PLI9nfbsAvV452GTMp/xlkoLcZGtsrHph3TWOQnWT8Q1AEpVVx1fweD8epUCv7wyCJ7uKTq6nJODdZm1mVDkwYIkF4ntpw0uKRONvAB8ePN2M="
#   on:
#     tags: true
