language: node_js

node_js:
- "node"

cache:
  directories:
    - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=null
  - DATABASE_MIGRATIONS_DIR=null
  - DATABASE_MIGRATIONS_TABLE=null
  - PGSSLMODE=require
  - SECRET_PATH=null
  - ORIGIN=null
  - CLIENTS=null
  - AUTH0_CLIENT_ID=null
  - AUTH0_DOMAIN=null
  - LOGGLY_TOKEN=null
  - LOGGLY_SUBDOMAIN=null
  - ROLLBAR_TOKEN=null
  - GEMFURY_USER=neoncity
  # GEMFURY_API_KEY=???
  - secure: "a3IN8718V6yDHnq983RmUdb6upuyecWdm1fIfGbV7xqstMF4kdMwKoWr/jOpCKgap07pobWBvHGQeuPxw28P2pXZ+/iA4GIY5vtZ67b/Yy3JNVWGoL3NRE6DcDrOEbrSaVuZpFEbCabk5G5M8KOHtZ6KZh7w9Q7X2a+bGh22qiqaI4GLfxCCQXQkHmwwQN+hiKRyoJ++7n5yLJAzVRtPjI2HTK7S8C/J2nU0n8ztIOUjN4ICvpoIZcFeRWfCcQ3Zbyqej81MBWQzs2P1LC1jB+xmSVFRizWwZhzmBWT8IcCy6Y0xDi4cDtc7p23HpWBwUhl/soT30F3t0ZnIYL5Ed0xItDcWslMowXjw4iQ3Hal13CCAikBQscaDLHZ5SBZ/tRCEF5B0Jv3om3pYXhTAwBmVr3I5ec+cfR/HWYJ7CehV2sVIrl4vP/EKpQdleJVegu55cWxfYfpFZ0W6hkTIhaIVtHuIhdmYgbpV+NqrxxR91uA/yOq/Qno8F0vAqRXSsk7LY1LcKYMzCDDPaLbKncDMY3cgJchyzIGRYfxpkPYEzAhvBeufupsafhL4wZ8vX/zb8697gxQz6m+kgR8WOuc7amMhHathxtGYJCM3bMR4RBt74BedBERe1LKp/MoiuomE3lfhgMGyrv8z+NwNg0iQYq24y0PRi/O3nBYypXc="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
# - provider: heroku
#   skip_cleanup: true
#   app: identity-staging-neoncity
#   api_key:
#     secure: "bkrJktWntQN9CX+C1/u3Hbg81EeJ7siSN6qgYC8l92vCe7KiguxpXa8LyYUmw/rtmCOBrYx51QWzBc2ivaDgrfFepjA4cMDgkTGUwCEJOYwos9Dq1S6AlQPiCsPoI/GtLCPbJf7cntf8iqJiMt4GfqUDEfvagCF5qOiphQtjmCY3wrFcDDB1PgbsBTYq596eEgKr1OcLt8965AL6Krad36WcpMRTTtqVujZdFR3U+VCWCfLd6N6NAWWt8+wUkjMmK2qzv8r1QyUDfmlJbhoh9SrTmP7nIjqhGmo0NTM/j4ANOic+17xhY9I93qTjpmiFO9OZcpa24L/928wMKYB0TH7EppRoODWzOd0PNdYtY3b5BWo2Uxt+HJPH9Mh9GL76A/6mlxNUTzKRo3/uiLloIWQLmEpETjbdMwS2YVpNrsBAEjdS1LO1NkesDXqzyxelODxTNn31tbfGvT/HAPq1/GhDy7gJa3MPdEAMaTMqfOM/Ursejx4sSrJDgsXKG0equJOwTrGY55NGkUUABUDJOM4hMkars/9Q88S+wVWUyV6ruWoKfDy/ljhBSBooT0PLI9nfbsAvV452GTMp/xlkoLcZGtsrHph3TWOQnWT8Q1AEpVVx1fweD8epUCv7wyCJ7uKTq6nJODdZm1mVDkwYIkF4ntpw0uKRONvAB8ePN2M="
